# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# OIT_SpeedTierPrepv01.py
# Created on: 2016-04-03 19:17:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: OIT_SpeedTierPrepv01 <output_gdb> <BB_Service_PLSS> <BB_Service_Wireless>
# Description: Use this tool to seperate business from residential.  Use results
# in OIT_SpeedTier tool.
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
output_gdb = arcpy.GetParameterAsText(0)
#if output_gdb == '#' or not output_gdb:
   # output_gdb = "C:\\GOIT\\BaseData\\workspace\\output.gdb" # provide a default value if unspecified

BB_Service_PLSS = arcpy.GetParameterAsText(1)
# if BB_Service_PLSS == '#' or not BB_Service_PLSS:
    # BB_Service_PLSS = "P:\\SBDDGP-ARRA Project\\BroadbandProductionArea\\April2016_ProvData\\2016_April_Final\\CO_SBDP_04_2016.gdb\\OIT_Colorado_Broadband\\BB_Service_PLSS" # provide a default value if unspecified

BB_Service_Wireless = arcpy.GetParameterAsText(2)
#if BB_Service_Wireless == '#' or not BB_Service_Wireless:
    #BB_Service_Wireless = "P:\\SBDDGP-ARRA Project\\BroadbandProductionArea\\April2016_ProvData\\2016_April_Final\\CO_SBDP_04_2016.gdb\\OIT_Colorado_Broadband\\BB_Service_Wireless" # provide a default value if unspecified

# Local variables:


# Process: select WIreless Residential
arcpy.Select_analysis(BB_Service_Wireless, "Wireless_Residential", "ENDUSERCAT = '1' OR ENDUSERCAT = '5'" )

# Process: select plss Residential
arcpy.Select_analysis(BB_Service_PLSS, "plssResidential", "ENDUSERCAT = '1' OR ENDUSERCAT = '5'")

# Process: select WIreless Commercial
arcpy.Select_analysis(BB_Service_Wireless, "Wireless_Commercial", "ENDUSERCAT = '2' OR ENDUSERCAT = '5'")

# Process: select plss commercial
arcpy.Select_analysis(BB_Service_PLSS, "plssCommercial", "ENDUSERCAT = '2' OR ENDUSERCAT = '5'")

