# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# oitBaseMetric_export.py
# Created on: 2015-10-02 08:44:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: oitBaseMetric_export <censusid>
# Description:
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments

censusid = "C:\\GOIT\\BaseData\\BaseMetricsGDB.gdb\\censusid" # provide a default value if unspecified

# Local variables:
ColoradoAddresses = "C:\\GOIT\\BaseData\\base_data.gdb\\ColoradoAddresses"
plss = "C:\\GOIT\\Production_OCT2015\\OITFinal\\OITFinalTemplate.gdb\\plss"
OIT_PLSS_QQ = "C:\\GOIT\\BaseData\\base_data.gdb\\OIT_PLSS_QQ"
IN_MEMORY = "IN_MEMORY\\"
workspace_gdb = "C:\\Users\\rezaghok\\Desktop\\SCRATCH\\oitMetrics\\workspace.gdb"
baseMetrics = "baseMetrics"
QQ_Template = "QQ_Template"
addressPointsOutside = "IN_MEMORY\\addressPointsOutside"
addressPLSSSJ = "IN_MEMORY\\addressPLSSSJ"
plssMerge = "C:\\Users\\rezaghok\\Desktop\\SCRATCH\\oitMetrics\\workspace.gdb\\plssMerge"
plssMerge_Dissolve = "C:\\Users\\rezaghok\\Desktop\\SCRATCH\\oitMetrics\\workspace.gdb\\plssMerge_Dissolve"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(OIT_PLSS_QQ, QQ_Template, "", workspace_gdb, "OBJECTID OBJECTID VISIBLE NONE;Shape Shape VISIBLE NONE;PLSSID PLSSID VISIBLE NONE;REFGRIDNO REFGRIDNO VISIBLE NONE;OIT_ID OIT_ID VISIBLE NONE;Shape_Length Shape_Length VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE")

# Process: Erase
arcpy.Erase_analysis(ColoradoAddresses, plss, addressPointsOutside, "")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(QQ_Template, addressPointsOutside, addressPLSSSJ, "JOIN_ONE_TO_ONE", "KEEP_COMMON", "PLSSID \"PLSS Township Identifier\" true true false 16 Text 0 0 ,First,#,QQ_Template,PLSSID,-1,-1;REFGRIDNO \"Reference Grid Number\" true true false 20 Text 0 0 ,First,#,QQ_Template,REFGRIDNO,-1,-1;OIT_ID \"OIT_ID\" true true false 4 Long 0 0 ,First,#,QQ_Template,OIT_ID,-1,-1;Shape_Length \"Shape_Length\" false true true 8 Double 0 0 ,First,#,QQ_Template,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0 ,First,#,QQ_Template,Shape_Area,-1,-1", "INTERSECT", "", "")

# Process: Merge
arcpy.Merge_management("C:\\GOIT\\Production_OCT2015\\OITFinal\\OITFinalTemplate.gdb\\plss;IN_MEMORY\\addressPLSSSJ", plssMerge, "PLSSID \"PLSSID\" true true false 16 Text 0 0 ,First,#,C:\\GOIT\\Production_OCT2015\\OITFinal\\OITFinalTemplate.gdb\\plss,PLSSID,-1,-1,IN_MEMORY\\addressPLSSSJ,PLSSID,-1,-1;OIT_ID \"OIT_ID\" true true false 4 Long 0 0 ,First,#,C:\\GOIT\\Production_OCT2015\\OITFinal\\OITFinalTemplate.gdb\\plss,OIT_ID,-1,-1,IN_MEMORY\\addressPLSSSJ,OIT_ID,-1,-1")

# Process: Dissolve
arcpy.Dissolve_management(plssMerge, plssMerge_Dissolve, "OIT_ID", "", "MULTI_PART", "DISSOLVE_LINES")

# Process: Intersect
arcpy.Intersect_analysis("C:\\Users\\rezaghok\\Desktop\\SCRATCH\\oitMetrics\\workspace.gdb\\plssMerge_Dissolve #;C:\\GOIT\\BaseData\\BaseMetricsGDB.gdb\\censusid #", "baseMetrics", "ALL", "", "INPUT")

